### ISSUE TITLE
Error compiling Chrome Extension

### ISSUE THREAD

**Issue by markhats** [Venryx/mobx-devtools-advanced#12]
Hi

I'm trying to use the Chrome extension. I get the following error when running `npm run start:chrome`

```
[tsl] ERROR in /dev/mobx/mobx-devtools-advanced/src/frontend/TabChanges/index.tsx(70,43)
      TS2345: Argument of type '{ firstLower_to_upper: boolean; hyphenLower_to_hyphenUpper: boolean; }' is not assignable to parameter of type '(modifierNames: { startLower_to_upper: (str: any) => any; startUpper_to_lower: (str: any) => any; spaceLower_to_spaceUpper: (str: any) => any; hyphenLower_to_hyphenUpper: (str: any) => any; lowerUpper_to_lowerSpaceLower: (str: any) => any; removeSpaces: (str: any) => any; removeHyphens: (str: any) => any; }) => ((st...'.
  Object literal may only specify known properties, and 'firstLower_to_upper' does not exist in type '(modifierNames: { startLower_to_upper: (str: any) => any; startUpper_to_lower: (str: any) => any; spaceLower_to_spaceUpper: (str: any) => any; hyphenLower_to_hyphenUpper: (str: any) => any; lowerUpper_to_lowerSpaceLower: (str: any) => any; removeSpaces: (str: any) => any; removeHyphens: (str: any) => any; }) => ((st...'.
```
Any ideas what the problem is?

Thanks.

**Comment by Venryx** [comment]
Try pulling the latest version, it contains this change:
* Fixed that the versions were not pinned for some libraries of mine which I haven't yet started strict versioning for. (which thus was causing the codebase to break when compiling)

Side note: I just recompiled locally, and while it does compile correctly now, the "Changes" panel appears to not be functioning in the app I'm currently working on. I don't know why it stopped working, but thought I should mention it. (I'll look into it, but people can use the regular MobX dev-tools Changes panel until then) [the Components panel works as expected, however, which is the more important one in my case]

Closing, but feel free to re-open if you hit the issue again.

**Comment by markhats** [comment]
Thanks - all now compiles OK.

The Changes panel works fine for me but strangely the Components one doesn't. It's blank when I first switch to it and if I click 'Refresh', I get the following errors in the console:

```
Backend store updated with: {@@name: "Object", @@mobxObject: false, @@type: "object", inferPaths: true, autoSerializeDepth: 7}@@name: "Object"@@mobxObject: false@@type: "object"inferPaths: trueautoSerializeDepth: 7__proto__: Object
backend.js:10390 

Uncaught TypeError: reactHook.fiberRoots.toJSON is not a function
    at backend.js:10390
    at backend.js:10857
    at Array.forEach (<anonymous>)
    at backend.js:10857
    at Array.forEach (<anonymous>)
    at Bridge.$handleMessage (backend.js:10853)
    at listener (backend.js:9915)
(anonymous) @ backend.js:10390
(anonymous) @ backend.js:10857
(anonymous) @ backend.js:10857
$handleMessage @ backend.js:10853
listener @ backend.js:9915
postMessage (async)
sendMessageToBackend @ contentScript.js:13937
handleMessageFromDevtools @ contentScript.js:13942
localhost/:1 

Denying load of chrome-extension://phbmeifmomapaoaeigpohokelhnkpoac/VectorStructs.js.map. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
index.js:1632 

GET chrome-extension://invalid/ net::ERR_FAILED
```

**Comment by Venryx** [comment]
Yeah I just hit the same issue, but *only* on some pages.

It seems that the `Set.toJSON` function is not a standard Ecmascript function, and I'd just thought it was due to it showing `[native code]` in the console. (it's actually added by [core-js](https://github.com/zloirock/core-js), apparently -- and I guess optimized to machine code by Chrome)

Working on the fix now. (replacing with `Array.from`)

**Comment by Venryx** [comment]
Okay, try pulling the latest version; the error should be resolved.

Note that the React version needs to be using Fiber (v16+) for it to retrieve the component tree.

**Comment by Venryx** [comment]
Does the latest code work for you? If so, feel free to close the issue. :)

**Comment by markhats** [comment]
Great - all working now. The Component panel is very cool!
